// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace PawrtalWeb.Models;

public partial class Appointment
{
    public Guid Id { get; set; }

    public Guid PetId { get; set; }

    public string OwnerEmail { get; set; }

    public string VetEmail { get; set; }

    public string Type { get; set; }

    public DateOnly Date { get; set; }

    public string TimeSlot { get; set; }

    public string Reason { get; set; }

    public string Status { get; set; }

    public DateTime CreatedAt { get; set; }

    public DateTime UpdatedAt { get; set; }

    public bool IsDeleted { get; set; }

    public DateTime? DeletedAt { get; set; }
}