// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace PawrtalWeb.Models;

public partial class GroomingRecord
{
    public Guid Id { get; set; }

    public Guid PetId { get; set; }

    public DateOnly Date { get; set; }

    public string GroomerName { get; set; }

    public string GroomingType { get; set; }

    public string CoatConditionBefore { get; set; }

    public string CoatStyleNotes { get; set; }

    public string Observations { get; set; }

    public bool IsVisibleToOwner { get; set; }

    public DateTime? CreatedAt { get; set; }

    public bool IsDeleted { get; set; }

    public DateTime? DeletedAt { get; set; }

    public virtual Pet Pet { get; set; }
}