// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace PawrtalWeb.Models;

public partial class HealthRecord
{
    public Guid Id { get; set; }

    public Guid PetId { get; set; }

    public string RecordType { get; set; }

    public string Title { get; set; }

    public string Description { get; set; }

    public DateOnly Date { get; set; }

    public string FileUrl { get; set; }

    public bool IsVisibleToOwner { get; set; }

    public string VetEmail { get; set; }

    public string VetName { get; set; }

    public DateTime CreatedAt { get; set; }

    public bool IsDeleted { get; set; }

    public DateTime? DeletedAt { get; set; }
}