// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace PawrtalWeb.Models;

public partial class JournalEntry
{
    public Guid Id { get; set; }

    public Guid PetId { get; set; }

    public string EntryType { get; set; }

    public string Title { get; set; }

    public string Content { get; set; }

    public DateOnly Date { get; set; }

    public string Mood { get; set; }

    public DateTime CreatedAt { get; set; }

    public bool IsDeleted { get; set; }

    public DateTime? DeletedAt { get; set; }
}