// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace PawrtalWeb.Models;

public partial class Medication
{
    public Guid Id { get; set; }

    public Guid PetId { get; set; }

    public string Name { get; set; }

    public string Dosage { get; set; }

    public string Frequency { get; set; }

    public DateOnly StartDate { get; set; }

    public DateOnly? EndDate { get; set; }

    public string Notes { get; set; }

    public bool IsActive { get; set; }

    public string PrescribedBy { get; set; }

    public DateTime CreatedAt { get; set; }

    public bool IsDeleted { get; set; }

    public DateTime? DeletedAt { get; set; }
}