// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace PawrtalWeb.Models;

public partial class Message
{
    public Guid Id { get; set; }

    public string SenderEmail { get; set; }

    public string ReceiverEmail { get; set; }

    public string Content { get; set; }

    public bool IsRead { get; set; }

    public DateTime CreatedAt { get; set; }

    public bool IsDeleted { get; set; }

    public DateTime? DeletedAt { get; set; }
}