// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace PawrtalWeb.Models;

public partial class Pet
{
    public Guid Id { get; set; }

    public string OwnerEmail { get; set; }

    public string Name { get; set; }

    public string Species { get; set; }

    public string Breed { get; set; }

    public DateOnly? DateOfBirth { get; set; }

    public string Gender { get; set; }

    public decimal? WeightKg { get; set; }

    public string Color { get; set; }

    public string MicrochipId { get; set; }

    public string PhotoUrl { get; set; }

    public bool IsNeutered { get; set; }

    public DateTime CreatedAt { get; set; }

    public DateTime UpdatedAt { get; set; }

    public bool IsDeleted { get; set; }

    public DateTime? DeletedAt { get; set; }

    public virtual ICollection<GroomingRecord> GroomingRecords { get; set; } = new List<GroomingRecord>();

    public virtual ICollection<PetAllergy> PetAllergies { get; set; } = new List<PetAllergy>();

    public virtual ICollection<PetMedicalCondition> PetMedicalConditions { get; set; } = new List<PetMedicalCondition>();
}