// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace PawrtalWeb.Models;

public partial class PetMedicalCondition
{
    public Guid PetId { get; set; }

    public string Value { get; set; }

    public virtual Pet Pet { get; set; }
}