// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace PawrtalWeb.Models;

public partial class User
{
    public Guid Id { get; set; }

    public string Email { get; set; }

    public string FullName { get; set; }

    public string UserType { get; set; }

    public string Phone { get; set; }

    public string Address { get; set; }

    public string AvatarUrl { get; set; }

    public string NotificationPrefsJson { get; set; }

    public DateTime CreatedAt { get; set; }

    public DateTime UpdatedAt { get; set; }

    public string ClinicName { get; set; }

    public string LicenseNumber { get; set; }

    public string Specialization { get; set; }

    public string PasswordHash { get; set; }

    public bool IsDeleted { get; set; }

    public DateTime? DeletedAt { get; set; }
}