// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace PawrtalWeb.Models;

public partial class Vaccination
{
    public Guid Id { get; set; }

    public Guid PetId { get; set; }

    public string VaccineName { get; set; }

    public DateOnly DateAdministered { get; set; }

    public DateOnly? NextDueDate { get; set; }

    public string BatchNumber { get; set; }

    public string Notes { get; set; }

    public string AdministeredBy { get; set; }

    public DateTime CreatedAt { get; set; }

    public bool IsDeleted { get; set; }

    public DateTime? DeletedAt { get; set; }
}