// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using Microsoft.EntityFrameworkCore;
using PawrtalWeb.Models;

namespace PawrtalWeb.Shared;

public partial class PawrtalDbContext : DbContext
{
    public PawrtalDbContext(DbContextOptions<PawrtalDbContext> options)
        : base(options)
    {
    }

    public virtual DbSet<Appointment> Appointments { get; set; }

    public virtual DbSet<GroomingRecord> GroomingRecords { get; set; }

    public virtual DbSet<HealthRecord> HealthRecords { get; set; }

    public virtual DbSet<JournalEntry> JournalEntries { get; set; }

    public virtual DbSet<Medication> Medications { get; set; }

    public virtual DbSet<Message> Messages { get; set; }

    public virtual DbSet<Notification> Notifications { get; set; }

    public virtual DbSet<Pet> Pets { get; set; }

    public virtual DbSet<PetAllergy> PetAllergies { get; set; }

    public virtual DbSet<PetMedicalCondition> PetMedicalConditions { get; set; }

    public virtual DbSet<User> Users { get; set; }

    public virtual DbSet<Vaccination> Vaccinations { get; set; }

    protected override void OnModelCreating(ModelBuilder modelBuilder)
    {
        modelBuilder.Entity<Appointment>(entity =>
        {
            entity.Property(e => e.Id).ValueGeneratedNever();
            entity.Property(e => e.OwnerEmail).HasMaxLength(320);
            entity.Property(e => e.Status)
                .IsRequired()
                .HasMaxLength(50);
            entity.Property(e => e.TimeSlot)
                .IsRequired()
                .HasMaxLength(20);
            entity.Property(e => e.Type)
                .IsRequired()
                .HasMaxLength(50);
            entity.Property(e => e.VetEmail).HasMaxLength(320);
        });

        modelBuilder.Entity<GroomingRecord>(entity =>
        {
            entity.HasKey(e => e.Id).HasName("PK__Grooming__3214EC07F1E5F056");

            entity.Property(e => e.Id).HasDefaultValueSql("(newid())");
            entity.Property(e => e.CoatConditionBefore).HasMaxLength(100);
            entity.Property(e => e.CoatStyleNotes).HasMaxLength(500);
            entity.Property(e => e.CreatedAt).HasDefaultValueSql("(getutcdate())");
            entity.Property(e => e.GroomerName).HasMaxLength(200);
            entity.Property(e => e.GroomingType)
                .IsRequired()
                .HasMaxLength(100);
            entity.Property(e => e.IsVisibleToOwner).HasDefaultValue(true);

            entity.HasOne(d => d.Pet).WithMany(p => p.GroomingRecords)
                .HasForeignKey(d => d.PetId)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK_GroomingRecords_Pet");
        });

        modelBuilder.Entity<HealthRecord>(entity =>
        {
            entity.Property(e => e.Id).ValueGeneratedNever();
            entity.Property(e => e.FileUrl).HasMaxLength(2000);
            entity.Property(e => e.RecordType)
                .IsRequired()
                .HasMaxLength(50);
            entity.Property(e => e.Title)
                .IsRequired()
                .HasMaxLength(200);
            entity.Property(e => e.VetEmail).HasMaxLength(320);
            entity.Property(e => e.VetName).HasMaxLength(200);
        });

        modelBuilder.Entity<JournalEntry>(entity =>
        {
            entity.Property(e => e.Id).ValueGeneratedNever();
            entity.Property(e => e.EntryType)
                .IsRequired()
                .HasMaxLength(50);
            entity.Property(e => e.Mood).HasMaxLength(50);
            entity.Property(e => e.Title)
                .IsRequired()
                .HasMaxLength(200);
        });

        modelBuilder.Entity<Medication>(entity =>
        {
            entity.Property(e => e.Id).ValueGeneratedNever();
            entity.Property(e => e.Dosage).HasMaxLength(100);
            entity.Property(e => e.Frequency).HasMaxLength(100);
            entity.Property(e => e.Name)
                .IsRequired()
                .HasMaxLength(200);
            entity.Property(e => e.PrescribedBy).HasMaxLength(200);
        });

        modelBuilder.Entity<Message>(entity =>
        {
            entity.Property(e => e.Id).ValueGeneratedNever();
            entity.Property(e => e.Content).IsRequired();
            entity.Property(e => e.ReceiverEmail)
                .IsRequired()
                .HasMaxLength(320);
            entity.Property(e => e.SenderEmail)
                .IsRequired()
                .HasMaxLength(320);
        });

        modelBuilder.Entity<Notification>(entity =>
        {
            entity.Property(e => e.Id).ValueGeneratedNever();
            entity.Property(e => e.Message).IsRequired();
            entity.Property(e => e.RelatedEntityType).HasMaxLength(100);
            entity.Property(e => e.Title)
                .IsRequired()
                .HasMaxLength(200);
            entity.Property(e => e.Type)
                .IsRequired()
                .HasMaxLength(50);
            entity.Property(e => e.UserEmail)
                .IsRequired()
                .HasMaxLength(320);
        });

        modelBuilder.Entity<Pet>(entity =>
        {
            entity.Property(e => e.Id).ValueGeneratedNever();
            entity.Property(e => e.Breed).HasMaxLength(200);
            entity.Property(e => e.Color).HasMaxLength(200);
            entity.Property(e => e.Gender).HasMaxLength(50);
            entity.Property(e => e.MicrochipId).HasMaxLength(100);
            entity.Property(e => e.Name)
                .IsRequired()
                .HasMaxLength(200);
            entity.Property(e => e.OwnerEmail).HasMaxLength(320);
            entity.Property(e => e.PhotoUrl).HasMaxLength(2000);
            entity.Property(e => e.Species)
                .IsRequired()
                .HasMaxLength(50);
            entity.Property(e => e.WeightKg).HasColumnType("decimal(6, 2)");
        });

        modelBuilder.Entity<PetAllergy>(entity =>
        {
            entity.HasKey(e => new { e.PetId, e.Value });

            entity.Property(e => e.Value).HasMaxLength(200);

            entity.HasOne(d => d.Pet).WithMany(p => p.PetAllergies).HasForeignKey(d => d.PetId);
        });

        modelBuilder.Entity<PetMedicalCondition>(entity =>
        {
            entity.HasKey(e => new { e.PetId, e.Value });

            entity.Property(e => e.Value).HasMaxLength(200);

            entity.HasOne(d => d.Pet).WithMany(p => p.PetMedicalConditions).HasForeignKey(d => d.PetId);
        });

        modelBuilder.Entity<User>(entity =>
        {
            entity.Property(e => e.Id).ValueGeneratedNever();
            entity.Property(e => e.Address).HasMaxLength(500);
            entity.Property(e => e.AvatarUrl).HasMaxLength(2000);
            entity.Property(e => e.ClinicName).HasMaxLength(200);
            entity.Property(e => e.Email)
                .IsRequired()
                .HasMaxLength(320);
            entity.Property(e => e.FullName).HasMaxLength(200);
            entity.Property(e => e.LicenseNumber).HasMaxLength(100);
            entity.Property(e => e.PasswordHash).HasMaxLength(200);
            entity.Property(e => e.Phone).HasMaxLength(50);
            entity.Property(e => e.Specialization).HasMaxLength(200);
            entity.Property(e => e.UserType).HasMaxLength(50);
        });

        modelBuilder.Entity<Vaccination>(entity =>
        {
            entity.Property(e => e.Id).ValueGeneratedNever();
            entity.Property(e => e.AdministeredBy).HasMaxLength(200);
            entity.Property(e => e.BatchNumber).HasMaxLength(100);
            entity.Property(e => e.VaccineName)
                .IsRequired()
                .HasMaxLength(200);
        });

        OnModelCreatingPartial(modelBuilder);
    }

    partial void OnModelCreatingPartial(ModelBuilder modelBuilder);
}